### ISSUE TITLE
Make Astrobee move

### ISSUE THREAD

**Issue by stevenkuntz** [colbybanbury/astrobee_CISC489#3]
Tried and failed

**Comment by evandeagelis15** [comment]
Found ros movement commands. Need to find mobility package for ros

**Comment by stevenkuntz** [comment]
ros is pain

steven@steven-Precision-5520:~/Documents/freeflyer$ rosrun mobility -move -pos "0.3 0.4"
[rospack] Error: package 'mobility' not found

**Comment by stevenkuntz** [comment]
It works! I needed to make sure I sourced the setup.bash in freeflyer_build/native/devel, and when calling mobility package nodes, use <rosrun mobility teleop -args>, even though the mobility/readme.md doesn't say to use teleop.
